### ISSUE TITLE
Rename ReifiedStyle to ComputedStyle

### ISSUE THREAD

**Issue by presiyan-ivanov** [lapce/floem#10]
I think [computed style](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) is a better name since most people will be familiar with it from web development.

**Comment by dzhou121** [comment]
@MinusGix What do you think?

**Comment by dzhou121** [comment]
Renamed in 9501077f721e3611894a1b0e0c506c971b50c971
