### ISSUE TITLE
Replace closures with `view::from_fn`

### ISSUE THREAD

**Issue by matthunz** [lapce/floem#104]
Hey love this project! 🤙

Is it possible to remove the closures from views to reduce the syntax noise? I'm assuming it's sometimes useful to use a closure, like for nested state,  but I think those cases could use `view::from_fn` where we could impl `View` for some `FromFn` type

**Comment by dzhou121** [comment]
Thanks for your interest. 

I'm not familiar with `FromFn`. Any simple example to show how it works?

**Comment by matthunz** [comment]
Something like https://doc.rust-lang.org/std/iter/fn.from_fn.html

Basically it would just exist to handle cases where you do want your view inside a closure. Then we could write `v_stack(text("Hello world!"))`  and `v_stack(view::from_fn(|| text("Hello world!")))`

**Comment by dzhou121** [comment]
Got it thanks for clarifying. 

The view has to be always inside a closure though because the child's id needs to be created based on the parent's id.

**Comment by matthunz** [comment]
Oh interesting sorry I didn't know. In that case couldn't views get their context from the `View` trait? If they're already being returned I feel like IDs can be created in one of those methods, similar to xilem.

**Comment by dzhou121** [comment]
I think I know how I can lose the closure now. Thank you so much for bringing this up!

**Comment by matthunz** [comment]
Awesome! Looking forward to checking it out

**Comment by dzhou121** [comment]
It's done in main now. I've also added `text()`. The couter example looks much better!

**Comment by matthunz** [comment]
For sure I think it looks great! Can't wait to try it out 👍
