### ISSUE TITLE
Clip view doesn't seem to anti-alias border-radius

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#109]
Border Radius applied to a stack
![Screenshot 2023-09-24 at 7 35 44 PM](https://github.com/lapce/floem/assets/13090441/70679ed7-d4c7-4a7e-9560-51035959d010)
Border radius applied to clip
![Screenshot 2023-09-24 at 7 35 40 PM](https://github.com/lapce/floem/assets/13090441/1cd97153-ad00-404f-b81a-bc69ca7d5536)

**Comment by Zoxc** [comment]
https://github.com/audulus/vger-rs/pull/17 should fix this.

**Comment by jrmoulton** [comment]
Looks like this was never completely integrated with lapce/vger or something has broken since then. Clip no longer clips at all with border_radius
