### ISSUE TITLE
Strange behaviour in examples/animations/src/main.rs

### ISSUE THREAD

**Issue by sekoyo** [lapce/floem#115]
You can see that `is_hovered` correctly goes from false to true but the resulting behavior is strange.

It only plays the animation when it goes back to `false` from being `true`:

https://github.com/lapce/floem/assets/760314/ca301ac8-1c75-4d19-864f-03490b7f3de4

It would also be interesting to know how to not initially play the animation on start up.

I like the syntax and solid-like approach to Floem. My favourite syntax that I've seen so far; clean and elegant... although `.animation(animation())` looks a little odd and confusing to me

**Comment by toger5** [comment]
I observed this as well. I played around with the animations in general and it was not too intuitiv. Maybe this is even the expected behaviour. It would be really nice to get some documentation on how animaitions are supposed to behave

**Comment by dzhou121** [comment]
Animation is still working in progress, in both API and functionalities.

**Comment by presiyan-ivanov** [comment]
I added some documentation to the [animation example](https://github.com/lapce/floem/tree/main/examples/animations)

**Comment by jrmoulton** [comment]
These issues have been fixed by the introduction of transitions in the styles and by the new animation engine
