### ISSUE TITLE
stylesheets / themes

### ISSUE THREAD

**Issue by gitmalong** [lapce/floem#133]
Hi!

As a lazy dev  I would like to slap a kind of stylesheet to my UI to get started with a beautiful UI. Is that something that should be handled by third party component libs?

**Comment by pieterdd** [comment]
Are you perhaps looking for a UI component library?

I'm in the process of setting one up for Floem: https://github.com/pieterdd/prettygooey/tree/floem-rewrite Note that this is an [unfinished development branch](https://github.com/pieterdd/prettygooey/pull/2).

**Comment by golota60** [comment]
Hey, I've just published a library named [oxytail](https://github.com/golota60/oxytail) also implementing a couple of styled widgets if you're interested.

**Comment by pieterdd** [comment]
Happy to see more choices pop up! I didn't expect the [floem-themes](https://github.com/topics/floem-themes) topic to welcome its first entry so quickly after it was added to the docs 😄

**Comment by ArcExp** [comment]
are sylesheets the only way to apply a dark theme/dark mode to a floem app? trying to figure out how floem works in this regard, for an app I'm working on

**Comment by ArcExp** [comment]
Thanks! I'll be using that in my app

**Comment by jrmoulton** [comment]
Cool! You might consider just copy/paste that entire file and use the parts that you want. That repo is full of experiments that I don't necessarily maintain.

**Comment by ArcExp** [comment]
Will do :)
