### ISSUE TITLE
Scaling problems when switching window between displays of different resolutions

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#18]
On MacOS when moving a window between monitors of different resolutions the window appears fine until a resize event. When a resize event happens the scaling is off in my case by either 1/2 or 2x depending on whether I'm moving between hi res to low res or the other way around. I haven't been able to find where the problem is originating from. 

My initial guess was that the display scale was set once upon window creation and then used later because the window always resizes properly on the resolution that it was created on but has issues when it is moved to a different resolution. But I couldn't find anything in the code that looked like it was caching the scale

**Comment by dzhou121** [comment]
That's probably because I haven't hooked up the ```scale``` event from glazier.
