### ISSUE TITLE
`img` or `svg` absolute positioned pattern with three issues

### ISSUE THREAD

**Issue by dominikwilkowski** [lapce/floem#183]
I am building a GUI app that contains an input field which I am trying to give the ability to clear when someone clicks on an x symbol.

I reduced my code the the simplest view below:
```rust
use floem::{
    reactive::create_rw_signal,
    style::{AlignContent, AlignItems, CursorStyle, Display, Position},
    view::View,
    views::{container, container_box, h_stack, label, svg, Decorators},
    widgets::text_input,
};

fn app_view() -> impl View {
    let search_icon = r##"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="#424242">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
    </svg>"##;

    let search_text = create_rw_signal("".to_string());

    h_stack((
        label(|| String::from("Search / Create:")).style(|s| {
            s.font_size(12.0)
                .padding(3.0)
                .padding_top(8.0)
                .padding_left(10.0)
        }),
        container_box(text_input(search_text).keyboard_navigatable().style(|s| {
            s.padding(5.0)
                .z_index(1)
                .width_full()
                .margin(3.0)
                .padding_right(30.0)
                .border_radius(2)
        }))
        .style(|s| s.width_full().z_index(1)),
        container(svg(move || search_icon.to_string()).style(|s| {
            s.z_index(6)
                .inset_top(7)
                .inset_right(4)
                .height(16.0)
                .width(16.0)
                .cursor(CursorStyle::Pointer)
        }))
        .on_click_stop(move |_| {
            search_text.set(String::from(""));
        })
        .style(move |s| {
            s.position(Position::Absolute)
                .height(30.0)
                .width(30.0)
                .display(Display::None)
                .align_items(AlignItems::Baseline)
                .align_content(AlignContent::Center)
                .padding_left(10.0)
                .z_index(5)
                .inset_top(0)
                .inset_right(3)
                .cursor(CursorStyle::Pointer)
                .hover(|s| s.cursor(CursorStyle::Pointer))
                .apply_if(!search_text.get().is_empty(), |s| s.display(Display::Flex))
        }),
    ))
    .style(|s| s.width_full().height(30.0))
}

fn main() {
    floem::launch(app_view);
}
```
This will compile something like this (on macos):
<img width="748" alt="image" src="https://github.com/lapce/floem/assets/1266923/a43c3350-2b7d-495c-bec0-dac43f95ab4f">
When you type something into the input the symbol appears:
<img width="748" alt="image" src="https://github.com/lapce/floem/assets/1266923/2d168793-5f8b-4794-a123-d57ed216d91a">

The inspector view of this layout:
![input4](https://github.com/lapce/floem/assets/1266923/3f2b491c-4107-4cbd-9e87-bb330fec6667)

This pattern has exposed three issues I will try my best to detail below:

## 1. The cursor not being respected on top of another element with a cursor directive
Unfortunately because it's over-layed above the text input the cursor shows the input cursor and not the `Pointer` as I declared in the code.
![input1](https://github.com/lapce/floem/assets/1266923/e72b646a-49fc-4c88-817f-ae9d85972949)

## 2. The bounding box of the area you can actually type in is significantly smaller than it seems
When you type you can only type to an arbitrary weird length:
![input2](https://github.com/lapce/floem/assets/1266923/3f8c5887-c22e-4aef-a7cd-276083d2f0c6)

## 3. It crashes sometimes
When I type something, then clear it with a click on the icon and then continue to type without clicking anything (in this case the letter `s`) it crashes. I assume because the focus is still on the symbol which is now being hidden with `display: none`?
![input3](https://github.com/lapce/floem/assets/1266923/e38ddfbb-806e-4fc9-b14d-0b2d35e5b7f3)
The error is:
```sh
thread 'main' panicked at /rustc/79e9716c980570bfd1f666e3b16ac583f0168962/library/alloc/src/string.rs:1538:9:
assertion failed: self.is_char_boundary(idx)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /Users/dominik/.cargo/git/checkouts/winit-1ee925e9c8358846/7608048/src/platform_impl/macos/app_state.rs:377:33:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

Hope this helps

**Comment by presiyan-ivanov** [comment]
Thanks so much for the detailed explanation and the MRE.

Currently text input does not respect the width defined in styles - I created #187 for that. 
 I added a fix for the crash when  the text is modified by user code in #185.

**Comment by dominikwilkowski** [comment]
@presiyan-ivanov thank you for writing and merging #187 
With the width now respected there is something funky going on once I start typing into the field.
Using the code above here is a recording:
![input](https://github.com/lapce/floem/assets/1266923/ad2fef53-0c05-4aa7-a634-82d7fe431661)

**Comment by presiyan-ivanov** [comment]
I see. It is not correctly handling percentage-based width. #191 Should fix it

**Comment by dominikwilkowski** [comment]
I just checked and all three issues have been fixed with the latest in `main`. Thank you :)
