### ISSUE TITLE
`virtual_stack` within a `v_stack` get's into an infinite loop

### ISSUE THREAD

**Issue by dominikwilkowski** [lapce/floem#246]
If you use the widget_gallery example and change the `list.rs` file to the below code you can reproduce this issue.
```rust
use floem::{
    reactive::create_signal,
    view::View,
    views::{
        label, v_stack, virtual_stack, Decorators, VirtualDirection, VirtualItemSize,
    },
};

pub fn virt_list_view() -> impl View {
    let field_list: im::Vector<i32> = (0..25).collect();
    let (dyn_field_list, _set_dyn_field_list) = create_signal(field_list);

    v_stack((
        label(move || "field"),
        label(move || "field"),
        label(move || "field"),
        label(move || "field"),
        label(move || "field"),
        virtual_stack(
            VirtualDirection::Vertical,
            VirtualItemSize::Fixed(Box::new(|| 31.0)),
            move || dyn_field_list.get(),
            move |item| *item,
            move |field| label(move || field).style(|s| s.height(31.0)),
        )
        .style(|s| s.gap(0, 5.0)),
    ))
    .style(|s| s.padding(8.0).width_full())
}
```

Edit: changed code to work after #248 
Edit 2: changed code to work after #251

**Comment by jrmoulton** [comment]
331	taffy::compute::compute_node_layout::h45313723ba884378	
331	taffy::compute::flexbox::compute::h65bcd4ee7171957c	
330 taffy::compute::flexbox::compute_preliminary::hccaabf1de1734bbb	
266	taffy::compute::compute_node_layout::h45313723ba884378	
265	taffy::compute::flexbox::compute::h65bcd4ee7171957c	
265	taffy::compute::flexbox::compute_preliminary::hccaabf1de1734bbb	
254	taffy::compute::compute_node_layout::h45313723ba884378	
251	taffy::compute::flexbox::compute::h65bcd4ee7171957c	
248	taffy::compute::flexbox::compute_preliminary::hccaabf1de1734bbb	
170	taffy::compute::compute_node_layout::h45313723ba884378	
150	taffy::compute::flexbox::compute::h65bcd4ee7171957c	
139	taffy::compute::flexbox::compute_preliminary::hccaabf1de1734bbb	
50	taffy::compute::flexbox::compute_preliminary::hccaabf1de1734bbb	


This is the a stack trace of the infinite loop as far as I can tell

**Comment by dominikwilkowski** [comment]
Replacing `virtual_stack` with the widget `virtual_list` fixes the issue but now I have to deal with the style opinions of that widget (hover color etc).

**Comment by jrmoulton** [comment]
You can disable the default widget styling. 

    app.window(
        app_logic,
        Some(
            WindowConfig::default()
                .themed(false)                <<<------ This 
                .with_transparent(true)
                .show_titlebar(false)
                .title("Leviathan")
                .size((300., 600.))
                .position(Point::new(1100., -500.)),
        ),
    )
    .run();

**Comment by dominikwilkowski** [comment]
Can you do that on a per-widget level?

**Comment by jrmoulton** [comment]
You can do style unset for specific properties

```rust
s.background(StyleValue::Unset)
```

but you need to do that for hover/active/etc. individually

**Comment by jrmoulton** [comment]
```rust
  .class(widgets::TooltipClass, |s| {
      s.background(StyleValue::Unset)
      .hover(|s| s.background(StyleValue::Unset)
  })
```

**Comment by Zoxc** [comment]
@dominikwilkowski You could also use `views::virtual_list` (with an extra container to match the widget variant if needed).
