### ISSUE TITLE
Visual regression on virtual list?

### ISSUE THREAD

**Issue by pieterdd** [lapce/floem#268]
I was preparing a [Floem update](https://github.com/pieterdd/floem-ui-kit/pull/1) in floem-ui-kit when I noticed some visual regression I didn't see on the main branch:

![image](https://github.com/lapce/floem/assets/1407980/51d244c6-a48b-4f77-b229-f229ee9731d7)

When removing other widgets and preserving only the radio group, this is what I see:

![image](https://github.com/lapce/floem/assets/1407980/dc335fa9-8449-41f7-bd2c-3b84343aae5a)

Could this be related to a recent Floem change, or should I change something on my end? This is the most important code change I did for the upgrade:

![image](https://github.com/lapce/floem/assets/1407980/7705dfc3-c434-4c2d-ba3e-51ac14a7feb9)

**Comment by Zoxc** [comment]
You probably implicitly changed from `virtual_stack` to `virtual_list`?

**Comment by pieterdd** [comment]
I will have a proper look tonight after work, but this example seems to be using the same `VirtualDirection` and `VirtualItemList` I am: https://github.com/lapce/floem/blob/9fc98fd6789beb1accc7af25291321ae3d0d9542/examples/virtual_list/src/main.rs#L17

I might be missing something so I'll do an in-depth comparison.

**Comment by pieterdd** [comment]
Did the semantics of the item_size parameter change by any chance? I might have unknowingly been relying on a bug to lay out my radio buttons horizontally. Previously, even with item_size `VirtualListItemSize::Fixed(Box::new(|| 1.0))` and a very long radio group button label, there was no overlap:

![image](https://github.com/lapce/floem/assets/1407980/9c2328ee-e7df-4464-90b3-5f5540c884c0)

The reason I started using `virtual_list` for this was to lay out a dynamic number of items horizontally. My use case is a generic radio group widget that takes an enum and renders all its options by relying on the Display trait.

**Comment by pieterdd** [comment]
Ah indeed, I need to use `virtual_stack` from now on:

![image](https://github.com/lapce/floem/assets/1407980/56474634-928e-4c83-82a5-2a587d83e68a)

**Comment by Zoxc** [comment]
It's probably a layout issue with horizontal `virtual_list`s.

You do have to correctly specify item sizes however, so you probably want to use `h_stack_from_iter` if you can't do that.

**Comment by pieterdd** [comment]
Having replaced `virtual_list` with `virtual_stack`, I'm still seeing a subtle difference. It looks like the `.gap(0.0, 20.0))` in the parent `v_stack` collapses in the new version:

Old Floem version with `virtual_list`:
![image](https://github.com/lapce/floem/assets/1407980/81a35522-cebe-4cfc-b99e-ab7451998c18)

New Floem version with `virtual_stack`:
![image](https://github.com/lapce/floem/assets/1407980/ce67c7b4-1aa7-4743-adfc-3dc10ba98e38)

Diff available [here](https://github.com/pieterdd/floem-ui-kit/pull/1/files#diff-fb152e6b25f855b2ac601a713662af7c65b801823f4843831d0eb46a755d865fL181-L186).

**Comment by pieterdd** [comment]
@Zoxc Our comments crossed, I'll give that a try - thanks!
