### ISSUE TITLE
Simplify Dropdown widget usage

### ISSUE THREAD

**Issue by habics** [lapce/floem#357]
I was looking forward for a Dropdown widget in floem and thankfully it exists now, but I looked at the example for it and was surprised how much boilerplate is required for it from a user's perspective, for example the user code is required to provide a [chevron icon](https://github.com/lapce/floem/blob/1ec918e673578df87558f43f4da91d3ee8849c09/examples/widget-gallery/src/dropdown.rs#L28) for it? and implement the default look [manually](https://github.com/lapce/floem/blob/1ec918e673578df87558f43f4da91d3ee8849c09/examples/widget-gallery/src/dropdown.rs#L36)? Isn't that what should be provided to user as the default look out of the box?
As a user I expect to give a dropdown widget a list of items and have a way to get the selected index and that's mostly it, like an array of strings or an enum with Display trait implemented for it to act as the items in the dropdown.

Thank you and I hope you can simplify the dropdown widget usage because now the library code is leaking too many details to the user.

**Comment by panekj** [comment]
> for example the user code is required to provide a [chevron icon](https://github.com/lapce/floem/blob/1ec918e673578df87558f43f4da91d3ee8849c09/examples/widget-gallery/src/dropdown.rs#L28) for it?

It's not required, as the directory name should suggest, it's an example, list works fine without an icon.

> and implement the default look [manually](https://github.com/lapce/floem/blob/1ec918e673578df87558f43f4da91d3ee8849c09/examples/widget-gallery/src/dropdown.rs#L36)?

I'm unsure what do you refer to as default look (since the links you gave point only to the example code file), below example works just as fine and isn't complicated

```rs
pub fn dropdown_view() -> impl View {
    let show_dropdown = create_rw_signal(false);

    form::form({
        (form_item("Dropdown".to_string(), 120.0, move || {
            dropdown(
                move || Values::Three,
                move |item| label(move || item).any(),
                Values::iter(),
                |item| label(move || item).any(),
            )
            .show_list(move || show_dropdown.get())
            .on_accept(move |_val| show_dropdown.set(false))
        }),)
    })
}
```

**Comment by jrmoulton** [comment]
Widgets in Floem are highly composable. The current dropdown widget is built to not lock you into any required style. If it was any simpler there would be aspects of the widget that you couldn't control. 

It might be a slight inconvenience to dial in the dropdown view just the way you want for a small project but once you've done it once you can just move that implementation to it's own function and reuse it. This is very practical even for small-medium projects. 

An opinionated widget would awesome but that sort of thing belongs in a separate widgets/components crate that provides a consistent look across all widgets and can build on the un-opinionated widgets that Floem provides

**Comment by habics** [comment]
Sorry guys closing the issue now, I didn't realize you can use simpler code than the one in the examples to create it, thank you for your awesome work on floem :)

**Comment by jrmoulton** [comment]
Thanks and now worries. Happy you're enjoying :)
