### ISSUE TITLE
Dropdown widget's height is taking 100% of parents remaining space.

### ISSUE THREAD

**Issue by habics** [lapce/floem#358]
![Untitled](https://github.com/lapce/floem/assets/161233868/5539ed09-92ca-4f68-9943-1c5869d2223e)

The dropdown widget shouldn't take all available height, expected result is similar to input widget which isn't taking 100% of available space.

**Comment by jrmoulton** [comment]
Looks like I set the dropdown to be size_full in the floem default theme (widgets/mod.rs). That should probably be changed/removed. For now you can override that using a .style on the dropdown and setting the height and width
