### ISSUE TITLE
floem found no Unfilled circle

### ISSUE THREAD

**Issue by 15artis** [lapce/floem#370]
When I attempt to add plotters, I need Unfilled circle, which is not found in floem. When I add stroke_arc in the local floem stroke, this function can be realized, but I have no permission to push it to the main warehouse

![1710098040030](https://github.com/lapce/floem/assets/49737709/67fbfd31-20db-455a-957f-8a0eb572ef8f)

**Comment by jrmoulton** [comment]
You can create a rounded rectangle and set the color to transparent and set a border or outline to get the same effect

**Comment by 15artis** [comment]
This solution can achieve the same effect, if you want to complete the circular progress bar, it may be difficult, kurbo library stroke arc can be solved very well

**Comment by jrmoulton** [comment]
> but I have no permission to push it to the main warehouse

What do you mean by this?

**Comment by 15artis** [comment]
I want to push code to floem

**Comment by panekj** [comment]
You can create a Pull Request if you want to add any changes
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by 15artis** [comment]
Thank you very much
