### ISSUE TITLE
[Editor] empty lines are skipped when navigating with keyboard

### ISSUE THREAD

**Issue by dominikwilkowski** [lapce/floem#390]
When in the editor and you have one or more empty lines and use the arrow keys <kbd>↑</kbd> or <kbd>↓</kbd> it skips the empty lines entirely and jumps to lines with text in them.
Mouse clicking into the empty lines works.

![empty_lines](https://github.com/lapce/floem/assets/1266923/39239fe7-1628-4545-8f49-d16d7aaedd9b)

**Comment by jrmoulton** [comment]
I don't have this issue. (although I'm not quite on latest main)

**Comment by dominikwilkowski** [comment]
The gif above is taken from the latest `main` editor example (no changes) on macos 14.4

**Comment by MinusGix** [comment]
I can reproduce this on latest main, might be a bug introduced because of my fixes to line handling. I'll look into it.
