### ISSUE TITLE
[Editor] ignores `style` function

### ISSUE THREAD

**Issue by dominikwilkowski** [lapce/floem#393]
The editor ignores `style` function right now.
It should either remove it which is hard with Decorator or support it to the extend that the container gets things border and display etc properties?

Maybe we explicitly say no styling for the editor and you have to use a `container` to wrap it to give it styles?
That only works if the container is always `.width_full()` and `.height_full()`?

**Comment by jrmoulton** [comment]
I’m working on an overhaul of editor styling right now

**Comment by dominikwilkowski** [comment]
fixed by #398
