### ISSUE TITLE
Editor selection no longer shows selection on empty lines

### ISSUE THREAD

**Issue by MinusGix** [lapce/floem#403]
![image](https://github.com/lapce/floem/assets/13157904/5203c00e-98db-4c02-945e-6d4ae91a7014)

Probably due to no longer including newlines in the visual line, so selection logic needs some +1 to size if the lines are empty.

**Comment by KhodyrevDS** [comment]
fixed https://github.com/lapce/floem/commit/b2fe244aca8128332ffcef38c882e931d0acdd1b
