### ISSUE TITLE
Left sidebar layout example is missing the last element

### ISSUE THREAD

**Issue by njust** [lapce/floem#428]
The last entry "99" is not visible:
![image](https://github.com/lapce/floem/assets/2380253/02f54f7c-7111-481f-8624-33ff5130145a)

The window height seems to affect the last visible elements.

With a small window, all items are visible:
![image](https://github.com/lapce/floem/assets/2380253/1aeca6f1-6bc8-44ed-ab02-ca06a12b7437)

With a big window, the last two items are not visible
![image](https://github.com/lapce/floem/assets/2380253/428b15e4-7454-4968-a3b6-f4a3b71b19dc)

**Comment by dominikwilkowski** [comment]
Oh yes I know why. Will fix today or tomorrow. Thanks for the report
