### ISSUE TITLE
KeyUp event not triggered

### ISSUE THREAD

**Issue by PhiSyX** [lapce/floem#436]
Hello.

Commit https://github.com/lapce/floem/commit/8f5a9c5c2bee1bb0355c7a058b6e39be42878534 breaks the behavior of the KeyUp event.

https://github.com/lapce/floem/blob/8f5a9c5c2bee1bb0355c7a058b6e39be42878534/src/views/decorator.rs#L142-L157

Line 148 of the `src/views/decorator.rs` file shows us that the enum variant used for `EventListener` is assigned to the `EventListener::KeyDown` variant instead of `EventListener::KeyUp`.

Thank you for all your hard work.

**Comment by dzhou121** [comment]
Thanks for pointing it out! It should be fixed now.

**Comment by PhiSyX** [comment]
Yes, it works, thank you!
