### ISSUE TITLE
Unresolved imports in Counter example

### ISSUE THREAD

**Issue by mari-rs** [lapce/floem#445]
Hello, I been encountering some strange issues with floem, to be specific `floem::IntoView` and `floem:::views::ButtonClass` do not seem to exist. To be honest, I feel like I am literally the only one with this issue, because if I look at all the countless examples, it seems not logical to me why it does not work for me. 

I got it to compile one time successfully but after that the issues occurred I described. 

I can **not guarantee** that the steps to reproduce will work on your system.

1. add floem with the version 0.1.1 to your cargo.toml
2. build the project
3. watch the error happening.

here are some screenshots of proof.
![da proof](https://github.com/lapce/floem/assets/98649425/ee0f4ff7-514a-4be1-9406-ace490aea819)

so if you are working with this crate and experience similar issues, I would kindly ask you to write it down in the comments I can't be the only one :c

anyway, if thats useful, here are my specs

- Ryzen 5 4500
- Rx 5700xt
- Asus rog strix b550-a 
- 32 gb | 3200mhz | Corsair vengeance rgb
- OS: macOS Monterey (12.7.4)

**Comment by panekj** [comment]
You used examples from `main` which is untagged floem and added `floem` in version `0.1.1`. You should be using examples from that version if you want it to work.

**Comment by mari-rs** [comment]
Ohh, my bad I didn't even realize, thank you so much 😭
