### ISSUE TITLE
Commit *Revert back to use CENTRAL_UPDATE_MESSAGES* breaks popups

### ISSUE THREAD

**Issue by timboudreau** [lapce/floem#448]
After pulling b83ae330cbacdb80b40a0aa5e5f2cf532f3448a6 locally, popups no longer work - neither mine, nor the popup in `floem::views::dropdown`.

Reverting that commit fixes the issue.

**Comment by timboudreau** [comment]
It appears messages are simply never delivered.

**Comment by jrmoulton** [comment]
There has been some discussion on this in the discord. Dzhou121 has a fix in mind

**Comment by dzhou121** [comment]
should be fixed by [c74beb1](https://github.com/lapce/floem/commit/c74beb142dd2611ff5a2f648e3bdb4b9437c9dc7)

**Comment by timboudreau** [comment]
Verified.  Popups work again.
