### ISSUE TITLE
No way to resign `active`

### ISSUE THREAD

**Issue by timboudreau** [lapce/floem#470]
`ViewId.requestActive()` is handy for being able to obtain drag events outside a components bounds (I wish I'd noticed it sooner than buried in a comment in `WindowHandle`).

However, once `active` is obtained, there is no way to *resign* from active-ness.  So you will get extra input events until - what? - something else takes over the active state?  It's not obvious how you escape from being active once you are.

It seems like the behavior of `active` should be stack-like - a view can push itself onto a stack of views the top-most of which is treated as active, and when it resigns `active`, we pop the next one (check if it still has a parent and if not keep popping) and it re-takes over as active.

That would make it possible to emulate the very useful Cocoa *first responder* pattern, which makes it trivial to implement things like bezier-spline editors that require immense amounts of bookkeeping in other frameworks.  It is basically having a stack of logic-objects that interpret input events.

There is also a case of cross-window `active` - my specific use case is popping up a popup window when a drag begins, the user drags to make an adjustment in it, and then releases the mouse to commit that adjustment.

I am thinking that might be better implemented as a separate "global-active" state, since in most cases, a view receiving events when another window is active would be non-intuitive behavior.

This all touches on issues in #465 - some of the state in `AppState` really should belong to the `ApplicationHandle` and other parts of it really belong to the `WindowHandle` - it needs to be teased apart into cross-window and non-cross window portions.

I've prototyped keeping a portion of `AppState` in the `ApplicationHandle`, updating the `WindowHandle`'s `AppState` before event processing, copying any changes back into the global state afterwards, and it is implementable and can be done without much overhead.

At any rate, providing a way to improve `active` handling can probably be handled as a separate PR without addressing the entire situation with `AppState`, so I'm filing this separately.

**Comment by jrmoulton** [comment]
> However, once active is obtained, there is no way to resign from active-ness. So you will get extra input events until - what? - something else takes over the active state? It's not obvious how you escape from being active once you are.

This is just missing from the API. We have a ViewId.clear_focus() but not a clear_active. 

> I am thinking that might be better implemented as a separate "global-active" state, since in most cases, a view receiving events when another window is active would be non-intuitive behavior.

Makes sense to me.

> It seems like the behavior of active should be stack-like - a view can push itself onto a stack of views the top-most of which is treated as active, and when it resigns active, we pop the next one (check if it still has a parent and if not keep popping) and it re-takes over as active.

I might not be seeing the vision on this idea. I feel like this would lead to unintuitive behavior if we implemented this

**Comment by timboudreau** [comment]
Hmm, looking at the way Active is handled, doing what I'm after across windows could wreak havoc with text input.

So, I think that there is something missing, but it is probably at least somewhat separate from "active".

**Comment by timboudreau** [comment]
[This PR](https://github.com/lapce/floem/pull/481) adds `ViewId.clear_active()` and associated plumbing.
