### ISSUE TITLE
Textedit with rich language support

### ISSUE THREAD

**Issue by FelixSiegel** [lapce/floem#494]
Hey, a friend and I are currently in the process of writing a small note app that will have markdown support. For this purpose, an entered text such as “# Heading” is to be formatted into a large heading.

 It would therefore be helpful if there was a rich language editor panel or something like that. Since there are already options for formatted text (bold, italic, font-size,...) it would only be practical if you could still edit this text.

**Comment by jrmoulton** [comment]
> it would only be practical if you could still edit this text.

Floem provides a `TextEditor` widget (the same text editor that is used in Lapce), that is what you should use if you want to edit the text. To do what you are looking for, `TextEditor` might need some modifications, but starting there will give you a much better place to start editing text. 

https://github.com/lapce/floem/tree/main/examples/syntax-editor

**Comment by FelixSiegel** [comment]
Oh, thank you very much for the quick reply! The example looks very good and what we need, I will take a look at it.
