### ISSUE TITLE
Hover Support

### ISSUE THREAD

**Issue by MinusGix** [lapce/floem#5]
It would be good to have an easy way to have things happen on hover.  
Implementation Suggestions:
[`AppState`](https://github.com/lapce/floem/blob/main/src/context.rs#L89) can have a `hover: Vec<Id>` which is just a list of all the currently hovered views. 
[`ViewState`](https://github.com/lapce/floem/blob/main/src/context.rs#L45) Can get a `hover_style: Option<Style>` (or just `Style::default()`) which is then applied in `fill_reified_style`, if the element is hovered.   
  
Then needs some code to detect when the mouse enters  
```rust
let rect = cx.get_size(self.id).unwrap_or_default().to_rect();
if rect.contains(event.pos) {
```
and set hover, and clear reified style cache  
And some code to detect when the mouse leaves, removing it from the hover list if it is in there and clearing reified style cache.  
Unsure where that logic should go.

**Comment by dzhou121** [comment]
I feel like the mouse enter/leave logic can be put in ```event_main``` in the View trait.
