### ISSUE TITLE
Inserting text in the middle of a textbox is impossible

### ISSUE THREAD

**Issue by meithecatte** [lapce/floem#532]
1. Open the Widget Gallery example
2. Choose "Input"
3. Type some text:
![image](https://github.com/user-attachments/assets/fbc8ae4b-1925-4b85-9f63-1c1ec28b7024)
4. Move the cursor:
![image](https://github.com/user-attachments/assets/fad77ee2-26d9-48fd-9fd6-d1d8652b409d)
5. Attempt inserting more text in the middle:
![image](https://github.com/user-attachments/assets/c65b31b5-a3f6-4bb1-93cf-15520bf26f8f)
6. The cursor jumps to the end of the textbox after the first keystroke.

**Comment by moon989** [comment]
so many bugs

**Comment by jrmoulton** [comment]
There are issues with the text input. If you need a fix for these issues in the meantime can you can use the text editor widget. It is overkill but it doesn't have the same issues.

**Comment by sgued** [comment]
This effect causes the issue:

https://github.com/lapce/floem/blob/8579753790f448f4248cd151c81cdc93383b944d/src/views/text_input.rs#L109-L113

Essentially any time the text is changed, the signal triggered, which updates triggers the effect, which the state, which then moves the cursor to the end:

https://github.com/lapce/floem/blob/8579753790f448f4248cd151c81cdc93383b944d/src/views/text_input.rs#L951-L954
