### ISSUE TITLE
Radio buttons are broken

### ISSUE THREAD

**Issue by meithecatte** [lapce/floem#533]
1. Open the Flight Booker example
![image](https://github.com/user-attachments/assets/74305dae-c02d-4260-b2f0-c705d4de290d)
2. Click "Return flight"
![image](https://github.com/user-attachments/assets/72d21ac6-94a6-415d-9c01-5b0b12e925a0)
3. Stare in disbelief

**Comment by sgued** [comment]
It's just the example that is broken. Radio buttons need to use `on_update` rather than add their own click handlers.

Fixed by #547
