### ISSUE TITLE
Use of unstable library feature 'lazy_cell' in /renderer/src/text/layout.rs

### ISSUE THREAD

**Issue by tcullum-rh** [lapce/floem#543]
I am trying to build my own floem-linked experimental program on Fedora 40, and I get these errors:

```
user@localhost ~/c/r/hello_floem (master) [101]> rustc --version
rustc 1.79.0 (129f3b996 2024-06-10)
user@localhost ~/c/r/hello_floem (master)> vim ./src/main.rs
user@localhost ~/c/r/hello_floem (master)> cargo run
   Compiling wgpu-core v22.1.0
   Compiling floem_renderer v0.1.1 (https://github.com/lapce/floem.git#a207ef4b)
   Compiling sctk-adwaita v0.7.0
   Compiling smithay-clipboard v0.7.2
error[E0658]: use of unstable library feature 'lazy_cell'
 --> /home/user/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:1:23
  |
1 | use std::{ops::Range, sync::LazyLock};
  |                       ^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/user/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:11:25
   |
11 | pub static FONT_SYSTEM: LazyLock<Mutex<FontSystem>> = LazyLock::new(|| {
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/user/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:11:55
   |
11 | pub static FONT_SYSTEM: LazyLock<Mutex<FontSystem>> = LazyLock::new(|| {
   |                                                       ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

error[E0658]: use of unstable library feature 'lazy_cell'
  --> /home/user/.cargo/git/checkouts/floem-69eea0a757d1e3ee/a207ef4/renderer/src/text/layout.rs:11:55
   |
11 | pub static FONT_SYSTEM: LazyLock<Mutex<FontSystem>> = LazyLock::new(|| {
   |                                                       ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `floem_renderer` (lib) due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
```

Is it known that unstable features are being used in `main` currently? Note that I am using rust 1.79 atm. I decided to just switch my `Cargo.toml` to use `floem = "0.1.1"` instead of pull from the main branch here and then I get this on `cargo run`:

```
cargo run
    Updating crates.io index
error: failed to select a version for `web-sys`.
    ... required by package `wgpu v0.18.0`
    ... which satisfies dependency `wgpu = "^0.18.0"` of package `floem_vger_renderer v0.1.0`
    ... which satisfies dependency `floem_vger_renderer = "^0.1.0"` of package `floem v0.1.1`
    ... which satisfies dependency `floem = "^0.1.1"` of package `hello_floem v0.1.0 (/home/moveax41h/code/rust/hello_floem)`
versions that meet the requirements `^0.3.64` (locked to 0.3.69) are: 0.3.69

the package `wgpu` depends on `web-sys`, with features: `GpuComputePassTimestampWrite` but `web-sys` does not have these features.


failed to select a version for `web-sys` which could resolve this conflict
```

The actual floem-linked program is this very simple test app:

```rust
use floem::window;
use floem::view::TextView;

fn main() {
    let app = window::Window::new("Hello, Floem", 800, 600);

    app.view(TextView::new("Hello, World!"));

    app.run();
}
```

**Comment by panekj** [comment]
> Is it known that unstable features are being used in `main` currently?

It's stable as of 1.80 which is the latest stable Rust version

**Comment by tcullum-rh** [comment]
> > Is it known that unstable features are being used in `main` currently?
> 
> It's stable as of 1.80 which is the latest stable Rust version

Is this _always_ the case? E.G. that it is stable for latest rust version only at any given time?

**Comment by panekj** [comment]
> Is this _always_ the case? E.G. that it is stable for latest rust version only at any given time?

I don't understand what exactly you're trying to ask here.
New features are unstable until stabilised. `lazy_cell` was unstable until Rust 1.80. It was stabilised in 1.80. Rust 1.80 is currently the latest stable version. Features are not retro-actively stabilised in previous versions.

**Comment by tcullum-rh** [comment]
@panekj Sorry if I was unclear. The question was whether or not `floem` development typically requires the latest version of rust at any given point in time?

**Comment by panekj** [comment]
Since Floem is actively developed and not deemed a stable interface, there isn't much reason to keep it working with older Rust versions. This might change once it matures and there are plans for stable release, e.g. v1.

I try to keep track of [MSRV](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) but in reality there is no automated tests and main consumer of Floem is Lapce which while might compile with older Rust versions sometimes, we don't guarantee it working with anything other that current latest stable.
