### ISSUE TITLE
floem = "0.1.1" doesn't work but floem = { git = "https://github.com/lapce/floem.git" } works fine.

### ISSUE THREAD

**Issue by indierusty** [lapce/floem#574]
priyanshu@pop-os:~/faster$ cargo add floem
    Updating crates.io index
      Adding floem v0.1.1 to dependencies
             Features:
             - serde
    Updating crates.io index
error: failed to select a version for the requirement `wgpu = "^0.18.0"`
candidate versions found which didn't match: 22.1.0, 22.0.0, 0.20.1, ...
location searched: crates.io index
required by package `floem_vger_renderer v0.1.0`
    ... which satisfies dependency `floem_vger_renderer = "^0.1.0"` of package `floem v0.1.1`
    ... which satisfies dependency `floem = "^0.1.1"` of package `faster v0.1.0 (/home/priyanshu/faster)`

**Comment by indierusty** [comment]
floem =

**Comment by JimitSoni18** [comment]
facing the same issue

**Comment by alexthegoodman** [comment]
@indierusty Thank you for the easy solution
