### ISSUE TITLE
img doesn't show anything

### ISSUE THREAD

**Issue by aalhitennf** [lapce/floem#587]
Smol example:  

```
use floem::{
    keyboard::{Key, Modifiers, NamedKey},
    taffy::AlignItems,
    views::{container, h_stack, img, Decorators},
    IntoView, View,
};

fn main() {
    floem::launch(main_view);
}

fn main_view() -> impl IntoView {
    let jpg_img = img(|| include_bytes!("../test.jpg").to_vec()).style(|s| s.size(200, 200));
    let png_img = img(|| include_bytes!("../test.png").to_vec()).style(|s| s.size(200, 200));

    let view = container(h_stack((jpg_img, png_img)))
        .style(|s| s.size_full().align_items(AlignItems::Center))
        .keyboard_navigatable();

    let id = view.id();

    view.on_key_up(Key::Named(NamedKey::F11), Modifiers::empty(), move |_| {
        id.inspect()
    })
}
```
Inspector shows that the layout is ok but nothing is drawn:

![floem_img](https://github.com/user-attachments/assets/901aadfd-d22b-4b35-abc1-ce068ddc7835)

Using git main on arch, wayland, amd gpu if any of that matters.

**Comment by jrmoulton** [comment]
Did this work with previously?

It looks like the widget gallery images still work. Do you have more info?

**Comment by aalhitennf** [comment]
Looks like i missed that support for different image types are now gated behind features and i didn't have default features enabled :grin:  :roll_eyes: Case closed :detective:

**Comment by jrmoulton** [comment]
We should probably at least print an error in that case
