### ISSUE TITLE
missing actions - open_file, save_as

### ISSUE THREAD

**Issue by JimitSoni18** [lapce/floem#612]
I tried the files example from the examples directory after adding floem dependency from the git repository, as i was getting #574 error with cargo add, and the code did not compile.
it gave me this errors:
```
   Compiling rxp v0.1.0 (/.../rxp)
error[E0432]: unresolved imports `floem::action::open_file`, `floem::action::save_as`
 --> src/main.rs:2:14
  |
2 |     action::{open_file, save_as},
  |              ^^^^^^^^^  ^^^^^^^ no `save_as` in `action`
  |              |
  |              no `open_file` in `action`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rxp` (bin "rxp") due to 1 previous error
```

**Comment by jrmoulton** [comment]
Are you sure you are using the latest main? I've just checked out latest main and don't have those issues.

**Comment by JimitSoni18** [comment]
sorry, i forgot to add features, closing the issue
