### ISSUE TITLE
Support views with single child dynamically updating

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#66]
Child views should update dynamically in response to signal changes. 

Eg.
```rust
fn wave_options(wave_type: ReadSignal<WaveType>) -> impl View {
    container_box(move || match wave_type.get() {
        WaveType::WaveSelect => Box::new(default_wave_options()),
        WaveType::CustomFunction => Box::new(custom_function()),
    })
    .style(|| Style::BASE.flex_col().width_pct(100.))
}
```

One thing to note though is that because the views are strongly typed any place where the child changes dynamically the possible children must all be of the exact same view type (which includes all children). Using BoxContainer would be necessary in any cases where the children weren't exactly the same. 

I tried implementing this on BoxContainer but kept running into issues

```rust
pub fn container_box(child: impl Fn() -> Box<dyn View> + 'static) -> ContainerBox {
    let cx = ViewContext::get_current();
    let id = cx.new_id();
    let mut curr_cx = cx;
    curr_cx.id = id;
    ViewContext::save();
    ViewContext::set_current(curr_cx);
    create_effect(cx.scope, move |_| {
        let child_id = curr_cx.new_id();
        let mut child_cx = curr_cx;
        child_cx.id = child_id;
        ViewContext::save();
        ViewContext::set_current(child_cx);
        let new_child = child();
        id.update_state(new_child, false);
        ViewContext::restore();
    });
    ViewContext::restore();
    let (_temp_child_id, temp_child) = ViewContext::new_id_with_child(crate::views::empty);
    ContainerBox {
        id,
        child: Box::new(temp_child),
    }
}
```

This is probably not the right approach. I run into issues with the ids. Inside of the effect I always get a mutable borrow error when creating the new id.
https://github.com/lapce/floem/blob/a0f29c6965f9d6bfe220cb410f0e58d2ed330250/src/id.rs#L68

Is there a different way I should be approaching this?

**Comment by jrmoulton** [comment]
> It's probably like this

For me this still panics in the same place with a borrow_mut error

**Comment by dzhou121** [comment]
It doesn't for me. Maybe paste the full trace?

**Comment by dzhou121** [comment]
It's because these two has already borrowed it. 

https://github.com/lapce/floem/blob/main/src/app_handle.rs#L654
https://github.com/lapce/floem/blob/main/src/app_handle.rs#L701

You'll need to get the id_path out like here https://github.com/lapce/floem/blob/main/src/app_handle.rs#L472

**Comment by jrmoulton** [comment]
Sweet! No longer panicking. But things are still showing up empty so I'm guessing that the child isn't getting the correct context. I'm not sure if that is a problem with my testing code or in container_box. In your test are you seeing elements populate correctly?

**Comment by dzhou121** [comment]
Is the new View appear in the ```update```?

**Comment by jrmoulton** [comment]
fn update(
        &mut self,
        cx: &mut crate::context::UpdateCx,
        state: Box<dyn std::any::Any>,
    ) -> crate::view::ChangeFlags {
        if let Ok(child) = state.downcast() {
            self.child = *child;
            cx.request_layout(self.id());
            ChangeFlags::LAYOUT
        } else {
            ChangeFlags::empty()
        }
    }

**Comment by jrmoulton** [comment]
I do get changes but not everything. It seems like it doesn't update the child views all the way down.

**Comment by jrmoulton** [comment]
> I mean you'll need to debug if the new child is actually sent to the `update`, or was it error in downcast.

Definitely getting the child in the update and no errors in downcast

**Comment by dzhou121** [comment]
Send a PR in. Maybe that would be easier.

**Comment by jrmoulton** [comment]
Added in #67
