### ISSUE TITLE
Simple List

### ISSUE THREAD

**Issue by MinusGix** [lapce/floem#86]
It might be nice to have a simple list UI element for easily displaying small numbers of elements.  
Similar to like you might use `label` for simple text, but use `rich_text` for more intricate display.  
  
-----

It would also be nice to let the simple list automatically compute element size, if that is possible. One annoyance with virtual list is having to know your element size beforehand.  

---

Example use case:  
A handful of predetermined tab headers that should just be automatically sized + positioned based on their container's width + padding.

**Comment by jrmoulton** [comment]
https://github.com/lapce/floem/blob/main/src/views/list.rs

I'm pretty sure `list` is what you're looking for

**Comment by MinusGix** [comment]
I.. somehow missed that. I keep missing the obvious pieces, I think I assumed that the widget gallery list example only using virtual list meant there was no other.. oops. Thanks.

**Comment by jrmoulton** [comment]
Haha no problem. I missed it too for a while for the exact same reason
