### ISSUE TITLE
Border Radius on HiDPI display

### ISSUE THREAD

**Issue by jrmoulton** [lapce/floem#97]
Seems like vger (best guess) doesn't render border radii correctly on HiDPI screens. Rounded rectangles look correct on my external display but on my MacBook built in display the corners aren't rounded properly

**Comment by dzhou121** [comment]
Probably because radius isn’t scaled. Can you try to double the radius and see if that would fix it?

**Comment by jrmoulton** [comment]
Doubling the border radius doesn't change anything. But when I add a edge_width to the scroll bar it does a cx.stroke on the shape and that does render correctly with the rounded edges. Not sure what is up there or why that changes between different displays

**Comment by jrmoulton** [comment]
fixed in d03f10ad7be03201c8508df00d153926a189d5ca
